// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignFileAssociation() {
  return window['go']['main']['App']['AssignFileAssociation']();
}

export function ChangeFile(arg1) {
  return window['go']['main']['App']['ChangeFile'](arg1);
}

export function CreateNewFile(arg1) {
  return window['go']['main']['App']['CreateNewFile'](arg1);
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveAsNewPassword(arg1, arg2) {
  return window['go']['main']['App']['SaveAsNewPassword'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function TryLoad() {
  return window['go']['main']['App']['TryLoad']();
}

export function UnlockFile(arg1) {
  return window['go']['main']['App']['UnlockFile'](arg1);
}
