// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFile(arg1:string):Promise<string>;

export function CreateNewFile(arg1:string):Promise<string>;

export function GetCurrentFile():Promise<string>;

export function GetFiles():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function TryLoad():Promise<string>;

export function UnlockFile(arg1:string):Promise<string>;
